// Objective-C API for talking to kotflow/mobile/sdk/kot Go package.
//   gobind -lang=objc kotflow/mobile/sdk/kot
//
// File is generated by gobind. Do not edit.

#ifndef __Kot_H__
#define __Kot_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class KotWallet;

@interface KotWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (NSString* _Nonnull)getAddress:(NSString* _Nullable)mnemonic error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getFee:(NSString* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (BOOL)isAddress:(NSString* _Nullable)address;
- (BOOL)isMnemonicValid:(NSString* _Nullable)mnemonic;
- (NSString* _Nonnull)newMnemonic:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT KotWallet* _Nullable KotNewWallet(void);

#endif
