
// Objective-C API for talking to the following Go packages
//
//	kotflow/mobile/sdk/kot
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Kot_FRAMEWORK_H__
#define __Kot_FRAMEWORK_H__

#include "Kot.objc.h"
#include "Universe.objc.h"

#endif
